version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack-prod
artifacts:
  files:
    - index.html
    - robots.txt
    - favicon.ico
    - images/*
    - styles/*
    - dist/*