version: 2.1

anchors:

  context: &context
    context: slack-notify

  filter_stage: &filter_stage
    filters:
      branches:
        only: ci-test


orbs:
  slack: circleci/slack@4.12.0

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1


jobs:
  build-assets:
    description: |
      - Runs NPM commands and better description goes here.
    docker:
      - image: cimg/node:18.12.1
    parallelism: 4
    steps:
      - checkout
      - run:
          command: echo $NODE_ENV && npm install
          name: install packages
      - run:
          command: npm run webpack-prod
          name: build static website assets
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - notify_slack_error
      - notify_slack_pass
    


workflows:
  build_deploy_stage:
    jobs:
      - build-assets:
          <<: *context
          <<: *filter_stage
  
# VS Code Extension Version: 1.4.0